# taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# packages
brew "git"
# brew "golang"
brew "jq"
brew "kubernetes-cli"
brew "terraform"
brew "nmap"
brew "derailed/k9s/k9s"
brew "awscli"
brew "pyenv"
brew "exa"
brew "rich"
brew "gh"
brew "direnv"

# Casks
cask "alfred"
cask "appcleaner"
# cask "cyberduck"
# cask "dropbox"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "spotify"
# cask "sublime-text"
cask "visual-studio-code"
cask "vlc"
cask "postman"