#! /usr/bin/env bash

# DESCRIPTION
# Installs Homebrew Casks.
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk8
brew cask install alfred
brew cask install appcleaner
brew cask install bettertouchtool
brew cask install cyberduck
brew cask install evernote
brew cask install dropbox
brew cask install docker
brew cask install google-chrome
brew cask install google-cloud-sdk
brew cask install iterm2
brew cask install itsycal
brew cask install little-snitch
brew cask install microsoft-office
brew cask install slack
brew cask install spectacle
brew cask install spotify
brew cask install sublime-text
brew cask install visual-studio-code
brew cask install vlc
